apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vrxq8cxaz-nodejs 
  janus-idp.io/tekton: vrxq8cxaz-nodejs
  backstage.io/kubernetes-id: vrxq8cxaz-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vrxq8cxaz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml