apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vrxq8cxaz-nodejs-gitops
  description: This is GitOps manifest for vrxq8cxaz-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=vrxq8cxaz-nodejs
    backstage.io/kubernetes-id: vrxq8cxaz-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vrxq8cxaz-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vrxq8cxaz-nodejs
