apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vrxq8cxaz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vrxq8cxaz-nodejs 
  name: vrxq8cxaz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vrxq8cxaz-nodejs 
